name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run build

      - name: List css contents
        run: |
          echo "=== css ==="
          ls -l css || echo "no css"

      - name: Prepare static files
        run: |
          rm -rf dist
          mkdir dist
          cp index.html dist/
          cp -r css dist/
          cp -r js dist/
          cp -r img dist/
          cp -r fonts dist/

      - name: List dist contents
        run: |
          echo "=== dist ==="
          ls -l dist
          echo "=== dist/css ==="
          ls -l dist/css || echo "no dist/css"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages 